"""profiles templates scripts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 08:41:45.074264
"""

from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('selling_points', sa.JSON(), nullable=False),
    sa.Column('product_details', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=200), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('call_to_action', sa.String(length=200), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('banned_words', sa.JSON(), nullable=False),
    sa.Column('voice_id', sa.String(length=40), nullable=False),
    sa.Column('voice_speed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_tenant_id'), 'brand_profiles', ['tenant_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('builtin_key', sa.String(length=48), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('shots', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('builtin_key')
    )
    op.create_index(op.f('ix_templates_tenant_id'), 'templates', ['tenant_id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('template_name', sa.String(length=80), nullable=False),
    sa.Column('profile_name', sa.String(length=80), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('hook', sa.String(length=300), nullable=False),
    sa.Column('shots', sa.JSON(), nullable=False),
    sa.Column('post_caption', sa.String(length=2200), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['brand_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_batch_id'), 'scripts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_scripts_profile_id'), 'scripts', ['profile_id'], unique=False)
    op.create_index(op.f('ix_scripts_status'), 'scripts', ['status'], unique=False)
    op.create_index(op.f('ix_scripts_template_id'), 'scripts', ['template_id'], unique=False)
    op.create_index('ix_scripts_tenant_created', 'scripts', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scripts_tenant_id'), 'scripts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_tenant_id'), table_name='scripts')
    op.drop_index('ix_scripts_tenant_created', table_name='scripts')
    op.drop_index(op.f('ix_scripts_template_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_status'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_profile_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_batch_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_templates_tenant_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_brand_profiles_tenant_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
