"""videos

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 09:16:24.291126
"""

from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('template_name', sa.String(length=80), nullable=False),
    sa.Column('profile_name', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=200), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('has_output', sa.Boolean(), nullable=False),
    sa.Column('render_seconds', sa.Float(), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['brand_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_batch_id'), 'videos', ['batch_id'], unique=False)
    op.create_index(op.f('ix_videos_profile_id'), 'videos', ['profile_id'], unique=False)
    op.create_index(op.f('ix_videos_script_id'), 'videos', ['script_id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index('ix_videos_tenant_created', 'videos', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_videos_tenant_id'), 'videos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_tenant_id'), table_name='videos')
    op.drop_index('ix_videos_tenant_created', table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_script_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_profile_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_batch_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
