"""music tracks：背景音樂庫，並為既有 kie 渠道加入 Suno 音樂模型

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-01 14:06:48.737995
"""

import uuid
from datetime import UTC, datetime

from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('style', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_tracks_status'), 'music_tracks', ['status'], unique=False)
    op.create_index(op.f('ix_music_tracks_tenant_id'), 'music_tracks', ['tenant_id'], unique=False)
    op.add_column('uploads', sa.Column('purpose', sa.String(length=16), server_default='asset', nullable=False))
    # ### end Alembic commands ###

    # 資料：既有 kie 渠道補上 Suno 音樂模型（租戶沒有預設音樂模型時設為預設）
    conn = op.get_bind()
    for channel_id, tenant_id in conn.execute(
        sa.text("SELECT id, tenant_id FROM model_channels WHERE provider = 'kie' ORDER BY created_at")
    ).all():
        exists = conn.execute(
            sa.text("SELECT 1 FROM channel_models WHERE channel_id = :c AND model_key = 'ai-music-api/generate'"),
            {"c": channel_id},
        ).first()
        if exists:
            continue
        has_default = conn.execute(
            sa.text(
                "SELECT 1 FROM channel_models cm JOIN model_channels mc ON mc.id = cm.channel_id "
                "WHERE mc.tenant_id = :t AND cm.capability = 'music' AND cm.is_default"
            ),
            {"t": tenant_id},
        ).first()
        conn.execute(
            sa.text(
                "INSERT INTO channel_models (id, channel_id, model_key, display_name, capability, is_default, enabled, created_at) "
                "VALUES (:id, :c, 'ai-music-api/generate', 'Suno 背景音樂', 'music', :d, true, :now)"
            ),
            {"id": str(uuid.uuid4()), "c": channel_id, "d": not has_default, "now": datetime.now(UTC)},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'purpose')
    op.drop_index(op.f('ix_music_tracks_tenant_id'), table_name='music_tracks')
    op.drop_index(op.f('ix_music_tracks_status'), table_name='music_tracks')
    op.drop_table('music_tracks')
    # ### end Alembic commands ###
