"""發佈帳號、排程與評論

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-05 09:31:27.325132
"""

from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('remote_profile', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('external_account_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_suggest_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_suggest_by', sa.String(length=36), nullable=True),
    sa.Column('auth_status', sa.String(length=32), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auto_suggest_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['publish_channels.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['brand_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'remote_profile', 'platform')
    )
    op.create_index(op.f('ix_social_accounts_channel_id'), 'social_accounts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_profile_id'), 'social_accounts', ['profile_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_tenant_id'), 'social_accounts', ['tenant_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('request_key', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2200), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('schedule_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('video_sha256', sa.String(length=64), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('remote_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_comment_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments_error', sa.String(length=500), nullable=False),
    sa.Column('comment_cursor', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'request_key')
    )
    op.create_index(op.f('ix_posts_account_id'), 'posts', ['account_id'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index('ix_posts_sync', 'posts', ['status', 'next_comment_sync_at'], unique=False)
    op.create_index(op.f('ix_posts_tenant_id'), 'posts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_posts_video_id'), 'posts', ['video_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('remote_id', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('suggested_reply', sa.String(length=2000), nullable=False),
    sa.Column('ai_status', sa.String(length=16), nullable=False),
    sa.Column('ai_error', sa.String(length=500), nullable=False),
    sa.Column('reply_status', sa.String(length=16), nullable=False),
    sa.Column('reply_text', sa.String(length=2000), nullable=False),
    sa.Column('remote_reply_id', sa.String(length=200), nullable=False),
    sa.Column('replied_by', sa.String(length=36), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['replied_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'remote_id')
    )
    op.create_index(op.f('ix_comments_intent'), 'comments', ['intent'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_reply_status'), 'comments', ['reply_status'], unique=False)
    op.create_index(op.f('ix_comments_tenant_id'), 'comments', ['tenant_id'], unique=False)
    op.add_column('usage_ledger', sa.Column('post_id', sa.String(length=36), nullable=True))
    op.add_column('usage_ledger', sa.Column('comment_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_usage_ledger_comment_id'), 'usage_ledger', ['comment_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_post_id'), 'usage_ledger', ['post_id'], unique=False)
    op.create_foreign_key('fk_usage_ledger_comment_id', 'usage_ledger', 'comments', ['comment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_usage_ledger_post_id', 'usage_ledger', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usage_ledger_post_id', 'usage_ledger', type_='foreignkey')
    op.drop_constraint('fk_usage_ledger_comment_id', 'usage_ledger', type_='foreignkey')
    op.drop_index(op.f('ix_usage_ledger_post_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_comment_id'), table_name='usage_ledger')
    op.drop_column('usage_ledger', 'comment_id')
    op.drop_column('usage_ledger', 'post_id')
    op.drop_index(op.f('ix_comments_tenant_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_reply_status'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_intent'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_video_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_tenant_id'), table_name='posts')
    op.drop_index('ix_posts_sync', table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_account_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_social_accounts_tenant_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_profile_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_channel_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
